FROM ubuntu:18.04
ENV container docker
RUN apt-get update && apt-get install -y wget
RUN apt-get update
CMD bash

RUN printf "deb https://oplab9.parqtec.unicamp.br/pub/repository/debian/ ./" >> /etc/apt/sources.list
